name: state_queue
description: A BLoC implementation for sequentially executed async state updates.
version: 1.1.0
authors:
  - Timm Preetz <timm.preetz@aboutyou.com>
  - Henri Beck <henri.beck@aboutyou.com>
homepage: https://github.com/aboutyou/dart_packages/tree/master/packages/state_queue
repository: https://github.com/aboutyou/dart_packages

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.7.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.0.0

  pending_operations: ^1.0.1

dev_dependencies:
  test: any

  pedantic: ^1.8.0+1

  flutter_test:
    sdk: flutter
